@PORT = 3000

@HOST = http://localhost:{{PORT}}

GET {{HOST}}/api/autores
Authorization: API-KEY

###
GET {{HOST}}/api/autores/autor/1
Authorization: API-KEY

###
POST {{HOST}}/api/autores
Authorization: API-KEY
Content-Type: application/json

{
    "nombre":"hola",
    "email":"lore2mIpsum@gmai1l.com",
    "imagen": "imagen.jpg"
}

